CREATE DATABASE todolist;
USE todolist;

CREATE TABLE todo (
id INT AUTO_INCREMENT PRIMARY KEY,
description VARCHAR(255) NOT NULL,
is_check TINYINT DEFAULT 0,
in_date DATETIME DEFAULT CURRENT_TIMESTAMP
)